name: flutte_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.4
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  path_provider: ^2.1.2
  crypto: ^3.0.3
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: pingFang-bold
      fonts:
        - asset: assets/fonts/pingFang-bold.ttf
